version: '3.4'

services:
  web.api:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Web.API/Dockerfile
    depends_on:
      - sqldata

  sqldata:
   container_name: sqldata
   image: mcr.microsoft.com/mssql/server:2022-latest
   environment:
     - SA_PASSWORD=Senha123!
     - ACCEPT_EULA=Y
